
[pytest]
cache_dir = .cache/pytest
testpaths = spec
pythonpath = .
python_files = *spec.py
python_classes = Test*
python_functions = test_*
addopts = --cov=kernel --cov=ops --cov-report=term-missing
